# 使用するNode.jsのバージョンを指定
FROM node:18

# アプリケーションのディレクトリを設定
WORKDIR /project

# npmを最新バージョンにアップグレード
RUN npm install -g npm@latest

# アプリケーションの依存関係ファイルをコンテナにコピー
# COPY package*.json ./

# 依存関係をインストール
# RUN npm install

# アプリケーションのソースをコンテナにコピー
# COPY . .
