version: 0.2
env:
  parameter-store:
    SSM_ENV_VALUE: "/ecs/${PROJECT_NAME}/${ENVIRONMENT}/${APP_NAME}/.env.public"

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "setting variables..."
      - APP_REPO_NAME=${PROJECT_NAME}-${ENVIRONMENT}-${APP_NAME}-app
      - REPOSITORY_URI_APP=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPO_NAME}

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo "copy env..."
      - echo "${SSM_ENV_VALUE}" > apps/${APP_NAME}/.env

      - echo "build..."
      - DOCKER_BUILDKIT=1 docker build -t ${REPOSITORY_URI_APP}:original -f apps/${APP_NAME}/docker/aws/nodejs/Dockerfile .

      - echo "docker tag..."
      - docker tag ${REPOSITORY_URI_APP}:original ${REPOSITORY_URI_APP}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker tag ${REPOSITORY_URI_APP}:original ${REPOSITORY_URI_APP}:latest

  post_build:
    commands:
      - echo "push to ECR..."
      - docker push ${REPOSITORY_URI_APP}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push ${REPOSITORY_URI_APP}:latest

      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' ${APP_REPO_NAME} ${REPOSITORY_URI_APP}:${CODEBUILD_RESOLVED_SOURCE_VERSION} > imagedefinitions-${APP_NAME}.json
artifacts:
  files: imagedefinitions-${APP_NAME}.json
