"""comment

Revision ID: 841acc7ed990
Revises:
Create Date: 2024-05-06 17:19:31.755366

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "841acc7ed990"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="メールアドレス"
        ),
        sa.Column(
            "password", sa.String(length=255), nullable=False, comment="パスワード"
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="アクティブかどうか"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="名前"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="メールアドレス"
        ),
        sa.Column(
            "password", sa.String(length=255), nullable=False, comment="パスワード"
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="アクティブかどうか"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="名前"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
