# name: Check and Test

# on:
#   push:
#     branches:
#       - prod
#     paths-ignore:
#       - '**.md'
#       - 'Makefile'
# jobs:
#   check-tests:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Copy .env
#       run: |
#         make cp-env

#     - name: Build and start Docker Compose services
#       run: |
#         make github-init

#     - name: Run check
#       run: |
#         make github-check

#     # - name: Run tests
#     #   run: |
#     #     make test
